[package]
name = "communicator"
version = "0.1.0"
authors = ["kaito2 <kaito.iwatsuki@nislab.doshisha.ac.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
